args <- commandArgs(trailingOnly=TRUE)
Q <- normalizePath(args[1]); D <- file.path(Q,"02_sources/common_member")
z <- read.delim(file.path(D,"sample_scores.tsv"))
expected <- read.delim(file.path(D,"all_program_contrasts.tsv"))
actual <- lapply(seq_len(nrow(expected)),function(i) {
 row <- expected[i,]; x <- subset(z,cohort==row$cohort & program==row$program)
 lev <- if(row$cohort=="GSE4797")c("JS10","JS8","JS5","JS2") else if(row$cohort=="GSE145467")c("normal","impaired") else c("OA","NOA")
 x$group <- factor(x$group,levels=lev)
 fit <- lm(score~group,data=x); co <- coef(summary(fit)); ci <- confint(fit)
 j <- nrow(co)
 stopifnot(isTRUE(all.equal(unname(co[j,1]),row$effect,tolerance=1e-10)),isTRUE(all.equal(unname(ci[j,]),c(row$CI_low,row$CI_high),tolerance=1e-10)),isTRUE(all.equal(unname(co[j,4]),row$p,tolerance=1e-10)))
 data.frame(cohort=row$cohort,program=row$program,effect_R=co[j,1],CI_low_R=ci[j,1],CI_high_R=ci[j,2],p_R=co[j,4],pass=TRUE)
})
actual <- do.call(rbind,actual)
stopifnot(isTRUE(all.equal(p.adjust(actual$p_R,"BH"),expected$BH_FDR_24_tests,tolerance=1e-10)))
write.table(actual,file.path(Q,"00_admin/common_member_independent_R_QA.tsv"),sep="\t",row.names=FALSE,quote=FALSE)
cat("PASS: independent R lm and confint verification of all 24 contrasts and BH family\n")
